deploy:
  name: Deploy Bicep to Azure
  runs-on: ubuntu-latest
  needs: lint
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: minecraft-dashboard-app

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep to Resource Group
      working-directory: minecraft-dashboard-app/infrastructure/bicep
      run: |
        az deployment group create \
          --resource-group MinecraftRG \
          --template-file appservice.bicep \
          --parameters sshPublicKey="${{ secrets.AZURE_SSH_KEY }}"